// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserService.Database;

namespace UserService.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("UserService.Database.Entities.AssignedRole", b =>
                {
                    b.Property<int>("AssignedRolesID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AssignToAdmin");

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Status");

                    b.Property<int>("UserID");

                    b.HasKey("AssignedRolesID");

                    b.ToTable("AssignedRoles");
                });

            modelBuilder.Entity("UserService.Database.Entities.Roles", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("RoleName");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("UserService.Database.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Birthdate");

                    b.Property<string>("ConfirmPassword");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<DateTime>("DateofJoining");

                    b.Property<string>("EmailID");

                    b.Property<string>("EmployeeID");

                    b.Property<int>("ForceChangePassword");

                    b.Property<string>("Gender");

                    b.Property<string>("Mobileno");

                    b.Property<string>("Name");

                    b.Property<string>("Password");

                    b.Property<int>("RoleID");

                    b.Property<string>("Username");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
